/**
 * A game's `.rules` files → one typed definition, with every name resolved.
 *
 * The parser refuses what it cannot *read*: an unknown kind, an unknown field,
 * a value outside a closed list, a required field left out. Everything that
 * needs a second declaration to check is here — a duplicate name, a phase
 * naming a step nothing declares, an action asking for a price that does not
 * exist, a trigger or a program naming a zone the game never declared, a
 * keyword hanging a body on a hook point the interpreter does not offer
 * (`docs/arena-rules-language.md` §3b, "what the loader refuses").
 *
 * Pure and synchronous, and **client-safe**: the files arrive as a map of name
 * → text (`dbs/files.ts`, generated by `scripts/arena-rulesets-emit.mts`), so
 * the app server, the browser and the scripts all take the same path and
 * nothing reads a file at request time.
 *
 * Nothing here *interprets* a declaration — that is Stage 4's `vm/`. The one
 * thing it does beyond checking is apply the schema's defaults, because the
 * printer drops none: a field left out of the text is `undefined`, and a
 * printer that dropped a value equal to its default could not bring it back
 * (#131).
 */
import type { Game } from "../../catalog/games";
import { CARD_ATTRS, COND_SCHEMA, DURATIONS, OP_SCHEMA, SIDES, type Amount, type Cond, type FieldType, type Op, type Ref, type Selector } from "../engine/script";
import type { SkillKindPrefix } from "../engine/types";
// Deep imports, not the `lang` barrel: the barrel binds `parseRule` to *this*
// module's own output (the game's words, #137), and the loader is what
// produces them. Reading the grammar directly is the one way round that
// circle, and it is the honest one — a `.rules` file is read against the
// engine's lists, and the areas it names are resolved against its own zones
// a few lines below.
import { fieldsOf, paramTypesFor, PARAM_TYPES, type Definition, type DefineField, type DefineHook, type DefineKind, type DefineRefusal, type PatternValue } from "../lang/ast";
import { parseDefinitions } from "../lang/parse";
import { holesIn } from "./holes";
import { isHookPoint, HOOK_POINTS } from "./hooks";
import type { GameDefinition, Loaded, RulesetError, Vocabulary } from "./types";

/**
 * The fields of a trigger's event pattern that name a zone. An event pattern
 * is open — which events a game fires is its own business — so the loader
 * cannot check every argument; these five are the ones that are a place, and
 * `moved(from: hand, to: battle)` is the wording the grammar was built for.
 *
 * Exported because the interpreter reads the same list for a second purpose
 * (`vm/triggers.ts`): a pattern that names a place is a pattern that says where
 * the answering card is or was, which is how 9-1-3-1's exceptions are derived
 * from the declarations instead of listed in code. One list, two readers.
 */
export const ZONE_ARGS = new Set(["from", "to", "in", "area", "zone"]);

/** The skill tags a card prints, as `SkillKindPrefix` spells them. No `DEFINE` kind declares these; the typecheck holds the list to the engine's. */
const SKILL_KINDS = ["auto", "activate", "counter", "permanent"] as const satisfies readonly SkillKindPrefix[];

/** `nth` is which declaration of this name in this file it is, 0-based, so a duplicate's error points at the *second* one — the line a person would delete. */
type Entry = { def: Definition; file: string; text: string; nth: number };

/**
 * Read a whole ruleset. `files` is file name → text; the names are sorted, so
 * two machines reading the same directory get the same declaration order and
 * the same first error.
 */
export function loadRuleset(files: Record<string, string>, id: Game = "dbs"): Loaded {
  const errors: RulesetError[] = [];
  const entries: Entry[] = [];
  const counted = new Map<string, number>();
  for (const file of Object.keys(files).sort()) {
    const text = files[file];
    const parsed = parseDefinitions(text);
    if (!parsed.ok) {
      errors.push({ ...parsed.error, file });
      continue;
    }
    for (const def of parsed.value) {
      const at = `${file}\u0000${keyOf(def)}`;
      const nth = counted.get(at) ?? 0;
      counted.set(at, nth + 1);
      entries.push({ def: withDefaults(def), file, text, nth });
    }
  }

  const definition: GameDefinition = {
    id,
    game: null,
    attributes: {},
    zones: {},
    phases: {},
    steps: {},
    actions: {},
    triggers: {},
    keywords: {},
    costs: {},
    wins: {},
    ops: {},
    words: {},
    prompts: {},
    definitions: entries.map((e) => e.def),
    sources: {},
  };

  // ── one declaration per name, per kind ───────────────────────────────────
  const seen = new Map<string, Entry>();
  const kept: Entry[] = [];
  for (const entry of entries) {
    const key = keyOf(entry.def);
    const first = seen.get(key);
    if (first) {
      errors.push(errorAt(entry, entry.def.name, `there is already a ${entry.def.define} called ${JSON.stringify(entry.def.name)}, declared in ${first.file}`, []));
      continue;
    }
    seen.set(key, entry);
    definition.sources[key] = entry.file;
    kept.push(entry);
    file(definition, entry.def);
  }

  // ── every name resolved against a declaration ────────────────────────────
  const promptKinds: Record<string, true> = {};
  for (const step of Object.values(definition.steps)) if (step.prompt) promptKinds[step.prompt] = true;
  for (const entry of kept) {
    const def = entry.def;
    const need = (names: readonly string[] | undefined, bucket: Record<string, unknown>, what: string) => {
      for (const name of names ?? []) {
        if (name in bucket) continue;
        errors.push(errorAt(entry, name, `${label(def)} names ${what} called ${JSON.stringify(name)}, which nothing declares`, Object.keys(bucket)));
      }
    };
    // The turn's phases, and the two a turn is not made of: a game that names
    // a setup or an over phase nothing declares would leave the flow runner
    // with nowhere to begin or to come to rest (#140).
    if (def.define === "GAME") need([...(def.phases ?? []), def.setupPhase, def.overPhase].filter((n): n is string => !!n), definition.phases, "a phase");
    if (def.define === "PHASE") {
      need(def.steps, definition.steps, "a step");
      need(def.actions, definition.actions, "an action");
    }
    if (def.define === "STEP") need([def.phase], definition.phases, "a phase");
    if (def.define === "ACTION") {
      need(def.when, definition.phases, "a phase");
      need(def.cost, definition.costs, "a price");
      // A question nothing asks is a move that can never be offered. The
      // prompts are whatever the steps ask for — `DEFINE PROMPT` is #131's open
      // question, so this reads the same list `vocabularyOf` does rather than
      // inventing a kind ahead of the answer.
      need(def.prompts, promptKinds, "a prompt");
    }
    // A price that reads its amount off a card reads it off a *declared*
    // attribute: `amount: costOf` is the whole of how 20-21's reductions reach
    // a play's price, and a name nothing declares would be a price of nothing.
    if (def.define === "COST") need(def.amount ? [def.amount] : [], definition.attributes, "an attribute");
    if (def.define === "TRIGGER") need(patternZones(def.on.args), definition.zones, "a zone");
    if (def.define === "KEYWORD") {
      for (const hook of def.hooks ?? []) {
        if (isHookPoint(hook.at)) continue;
        errors.push(errorAt(entry, hook.at, `${label(def)} hangs a body on ${JSON.stringify(hook.at)}, which is not a hook point the engine offers`, [...HOOK_POINTS]));
      }
    }
    // A macro's body may leave a value to the call — `$until`, `$ops`, `TOP $n`
    // — and every such hole names a parameter the macro takes, of a type the
    // slot can hold (#273). A `$n` in an amount or ref position is the same
    // node as a program's own binding, so there only a name the macro *takes*
    // is checked; anywhere else a `$name` is a hole and nothing else.
    if (def.define === "OP") {
      const takes = new Map((def.takes ?? []).map((p) => [p.name, p.type]));
      for (const hole of holesIn(def.do)) {
        const declared = takes.get(hole.name);
        if (declared === undefined) {
          if (hole.form === "var") continue;
          errors.push(errorAt(entry, `$${hole.name}`, `${label(def)} writes $${hole.name} in ${hole.where}, which is not a parameter it TAKES`, [...takes.keys()]));
          continue;
        }
        const allowed = paramTypesFor(hole.slot);
        if (allowed.includes(declared)) continue;
        errors.push(errorAt(entry, `$${hole.name}`, `${label(def)} writes $${hole.name} in ${hole.where}, which holds ${slotWord(hole.slot)}, but TAKES it as ${declared}`, allowed.filter((t) => (PARAM_TYPES as readonly string[]).includes(t))));
      }
    }
    // Every program and every selector names its areas, wherever it sits.
    need(areasOf(def), definition.zones, "a zone");
    // Every `modifyAttr` names an attribute of one of `CARD_ATTRS` — the
    // engine's own closed list — but that list is not the game's: a
    // declaration reaching for one nothing declares would apply to an
    // attribute no layer reads (#328).
    need(attributesOf(def), definition.attributes, "an attribute");
  }

  if (errors.length) return { ok: false, errors };
  return { ok: true, definition, vocabulary: vocabularyOf(definition) };
}

/** The word lists this definition fixes, in the names the language's constants already use. */
export function vocabularyOf(def: GameDefinition): Vocabulary {
  const words: Record<string, string> = {};
  for (const d of def.definitions) {
    const text = "text" in d ? d.text : undefined;
    if (typeof text === "string" && text) words[keyOf(d)] = text;
  }
  if (def.game?.title) words[keyOf(def.game)] = def.game.title;
  return {
    areas: Object.keys(def.zones),
    // No `DEFINE` kind declares a duration or a side: they are the effect
    // language's own words, and a game that needed different ones would need
    // a kind of its own rather than a longer list here.
    durations: [...DURATIONS],
    sides: [...SIDES],
    keywordNames: Object.keys(def.keywords),
    triggers: Object.keys(def.triggers),
    skillKinds: [...SKILL_KINDS],
    // The only place the grammar names a prompt today. `DEFINE PROMPT` is the
    // owner's open question on #131; until it is answered this is what the
    // steps ask for and nothing more.
    promptKinds: [
      ...new Set(
        Object.values(def.steps)
          .map((s) => s.prompt)
          .filter((p): p is string => !!p),
      ),
    ].sort(),
    words,
  };
}

// ── filing and defaults ─────────────────────────────────────────────────────

const keyOf = (def: Definition): string => `${def.define.toLowerCase()}:${def.name}`;
/** A slot's type in words, for the mismatch message: `a duration`, `one of [active, rest]`, `a list of strings`. */
const slotWord = (slot: FieldType | "number" | "side" | "area"): string => {
  if (typeof slot === "object") return "enum" in slot ? `one of [${slot.enum.join(", ")}]` : typeof slot.list === "object" ? `a list of [${slot.list.enum.join(", ")}]` : "a list of strings";
  return `${/^[aeiou]/.test(slot) ? "an" : "a"} ${slot}`;
};
const label = (def: Definition): string => `${def.define} ${JSON.stringify(def.name)}`;

/** Which record a declaration goes in. One case per kind, so a twelfth kind fails the typecheck rather than going missing. */
function file(into: GameDefinition, def: Definition): void {
  switch (def.define) {
    case "GAME":
      into.game = def;
      return;
    case "ATTRIBUTE":
      into.attributes[def.name] = def;
      return;
    case "ZONE":
      into.zones[def.name] = def;
      return;
    case "PHASE":
      into.phases[def.name] = def;
      return;
    case "STEP":
      into.steps[def.name] = def;
      return;
    case "ACTION":
      into.actions[def.name] = def;
      return;
    case "TRIGGER":
      into.triggers[def.name] = def;
      return;
    case "KEYWORD":
      into.keywords[def.name] = def;
      return;
    case "COST":
      into.costs[def.name] = def;
      return;
    case "WIN":
      into.wins[def.name] = def;
      return;
    case "OP":
      into.ops[def.name] = def;
      return;
    case "WORDS":
      into.words[def.name] = def;
      return;
    case "PROMPT":
      into.prompts[def.name] = def;
      return;
  }
}

/**
 * The schema's defaults, applied. Every default in `DEFINE_SCHEMA` is a scalar
 * (`players: 2`); a default that was an object would have to be copied here,
 * or two declarations would share one value.
 */
function withDefaults(def: Definition): Definition {
  const out = { ...def } as Record<string, unknown>;
  for (const f of fieldsOf(def.define) as readonly DefineField[]) {
    if (out[f.name] === undefined && f.default !== undefined) out[f.name] = f.default;
  }
  return out as unknown as Definition;
}

// ── the zones a declaration names ───────────────────────────────────────────

/** The zone-shaped arguments of a trigger's event pattern: `moved(from: hand, to: battle)`. */
function patternZones(args: Record<string, PatternValue>): string[] {
  const out: string[] = [];
  for (const [name, value] of Object.entries(args)) {
    if (!ZONE_ARGS.has(name)) continue;
    for (const v of Array.isArray(value) ? value : [value]) if (typeof v === "string") out.push(v);
  }
  return out;
}

/**
 * Every area any part of a declaration names — a `moveTo`'s `to`, a selector's
 * `area`, a condition nested three programs deep. Driven by the schema rows
 * rather than by a list of places, so an op that grows an area field is
 * checked the day its row says so.
 */
function areasOf(def: Definition): string[] {
  const out: string[] = [];
  for (const f of fieldsOf(def.define) as readonly DefineField[]) {
    const value = (def as unknown as Record<string, unknown>)[f.name];
    if (value === undefined || value === null) continue;
    if (f.type === "hooks") {
      for (const hook of value as DefineHook[]) out.push(...opsAreas(hook.ops));
      continue;
    }
    // An action's refusals: the condition that would have satisfied each one
    // selects cards, and a refusal pointing at a zone the game never declared
    // is a move that can never be explained.
    if (f.type === "refusals") {
      for (const refusal of value as DefineRefusal[]) out.push(...condAreas(refusal.unless));
      continue;
    }
    // A pattern's zones are read by `patternZones` (only some of its arguments
    // are places), and a parameter list names types, not areas.
    if (f.type === "pattern" || f.type === "params") continue;
    out.push(...fieldAreas(f.type, value));
  }
  return [...new Set(out)];
}

function fieldAreas(type: FieldType, value: unknown): string[] {
  if (typeof type === "object") return [];
  switch (type) {
    case "area":
      return typeof value === "string" ? [value] : [];
    case "selector":
      return selectorAreas(value as Selector);
    case "ref":
      return refAreas(value as Ref);
    case "amount":
      return amountAreas(value as Amount);
    case "cond":
      return condAreas(value as Cond);
    case "conds":
      return (value as Cond[]).flatMap(condAreas);
    case "ops":
      return opsAreas(value as Op[]);
    case "modes":
      return (value as { ops: Op[] }[]).flatMap((m) => opsAreas(m.ops ?? []));
    default:
      return [];
  }
}

function selectorAreas(sel: Selector | undefined): string[] {
  if (!sel || typeof sel !== "object") return [];
  return [...(sel.area ? [sel.area] : []), ...(sel.areas ?? []), ...selectorAreas(sel.underHost)];
}

const refAreas = (ref: Ref | undefined): string[] => (ref && typeof ref === "object" && "sel" in ref ? selectorAreas(ref.sel) : []);

/** Every area an expression names. `sumOf` before `attr`: the two share an `attr` key, so the narrower test has to come first (20-5). */
function amountAreas(amount: Amount | undefined): string[] {
  if (!amount || typeof amount !== "object") return [];
  if ("plus" in amount) return amountAreas(amount.plus[0]);
  if ("count" in amount) return selectorAreas(amount.count);
  if ("markers" in amount) return selectorAreas(amount.markers);
  if ("sumOf" in amount) return selectorAreas(amount.sumOf);
  if ("attr" in amount) return refAreas(amount.attr);
  return [];
}

function condAreas(cond: Cond | undefined): string[] {
  const spec = cond && typeof cond === "object" ? COND_SCHEMA[cond.kind] : undefined;
  if (!spec) return [];
  return spec.fields.flatMap((f) => fieldAreas(f.type, (cond as unknown as Record<string, unknown>)[f.name])).filter(Boolean);
}

function opsAreas(ops: Op[] | undefined): string[] {
  if (!Array.isArray(ops)) return [];
  return ops.flatMap((op) => {
    const spec = op && typeof op === "object" ? OP_SCHEMA[op.op] : undefined;
    if (!spec) return [];
    return spec.fields.flatMap((f) => {
      const value = (op as unknown as Record<string, unknown>)[f.name];
      return value === undefined || value === null ? [] : fieldAreas(f.type, value);
    });
  });
}

// ── the attributes a declaration names ──────────────────────────────────────

/**
 * Every attribute any part of a declaration names, walked the same way
 * `areasOf` walks zones. Today that is only `modifyAttr`'s own `attr:` field —
 * in a `DO`, a `HOOK` body or a macro body — but the walk is driven by which
 * op field the schema types against `CARD_ATTRS` (`isCardAttrField`, found by
 * identity rather than by op name), so a second op reaching for the same
 * closed list is checked the day its row says so, with no new case here.
 */
function attributesOf(def: Definition): string[] {
  const out: string[] = [];
  for (const f of fieldsOf(def.define) as readonly DefineField[]) {
    const value = (def as unknown as Record<string, unknown>)[f.name];
    if (value === undefined || value === null) continue;
    if (f.type === "hooks") {
      for (const hook of value as DefineHook[]) out.push(...opsAttrs(hook.ops));
      continue;
    }
    if (f.type === "refusals") {
      for (const refusal of value as DefineRefusal[]) out.push(...condAttrs(refusal.unless));
      continue;
    }
    if (f.type === "pattern" || f.type === "params") continue;
    out.push(...fieldAttrs(f.type, value));
  }
  return [...new Set(out)];
}

/** A field's type, as far as `attributesOf` cares: only `cond`/`conds`/`ops`/`modes` can nest an op that names an attribute. */
function fieldAttrs(type: FieldType, value: unknown): string[] {
  if (typeof type === "object") return [];
  switch (type) {
    case "cond":
      return condAttrs(value as Cond);
    case "conds":
      return (value as Cond[]).flatMap(condAttrs);
    case "ops":
      return opsAttrs(value as Op[]);
    case "modes":
      return (value as { ops: Op[] }[]).flatMap((m) => opsAttrs(m.ops ?? []));
    default:
      return [];
  }
}

function condAttrs(cond: Cond | undefined): string[] {
  const spec = cond && typeof cond === "object" ? COND_SCHEMA[cond.kind] : undefined;
  if (!spec) return [];
  return spec.fields.flatMap((f) => fieldAttrs(f.type, (cond as unknown as Record<string, unknown>)[f.name])).filter(Boolean);
}

/** A field the schema types against `CARD_ATTRS` — found by identity, since that one array is the engine's single closed list of attribute names (`modifyAttr`'s own `attr` field today). */
const isCardAttrField = (type: FieldType): boolean => typeof type === "object" && "enum" in type && type.enum === CARD_ATTRS;

function opsAttrs(ops: Op[] | undefined): string[] {
  if (!Array.isArray(ops)) return [];
  return ops.flatMap((op) => {
    const spec = op && typeof op === "object" ? OP_SCHEMA[op.op] : undefined;
    if (!spec) return [];
    return spec.fields.flatMap((f) => {
      const value = (op as unknown as Record<string, unknown>)[f.name];
      if (value === undefined || value === null) return [];
      if (isCardAttrField(f.type)) return typeof value === "string" ? [value] : [];
      return fieldAttrs(f.type, value);
    });
  });
}

// ── pointing at the place ───────────────────────────────────────────────────

/**
 * The error, at the line a person can open. A declaration carries no position
 * — the parser's tree is the text made into a tree, and adding one to every
 * node would be a change to the grammar for the loader's benefit — so the
 * declaration is found again in its own file by its header, and the offending
 * word inside its body.
 */
function errorAt(entry: Entry, needle: string, message: string, expected: string[]): RulesetError {
  const lines = entry.text.split(/\r?\n/);
  const head = new RegExp(`^\\s*DEFINE\\s+${entry.def.define}\\s+"?${escapeRe(entry.def.name)}"?\\s*(--.*)?$`, "i");
  let start = 0;
  let left = entry.nth;
  for (let i = 0; i < lines.length; i++) {
    if (!head.test(lines[i])) continue;
    start = i;
    if (left-- <= 0) break;
  }
  let end = start + 1;
  while (end < lines.length && !/^\s*DEFINE\b/i.test(lines[end])) end++;
  for (let i = start; i < end; i++) {
    const col = lines[i].indexOf(needle);
    if (col >= 0) return { file: entry.file, line: i + 1, col: col + 1, lineText: lines[i], clause: entry.def.define as DefineKind, message, expected };
  }
  return { file: entry.file, line: start + 1, col: 1, lineText: lines[start] ?? "", clause: entry.def.define as DefineKind, message, expected };
}

const escapeRe = (s: string): string => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
