/**
 * Generated by `npm run arena:rulesets` from `src/lib/arena/rulesets/dbs/*.rules`.
 * Do not edit: edit the `.rules` file and run the script again.
 *
 * The text lives here so the loader can be pure — see the script's header.
 */
export const FILES: Record<string, string> = {};
