/**
 * The `.rules` files, as string constants the app can import.
 *
 * `src/lib/arena/rulesets/load.ts` takes file name → text and never touches a
 * filesystem, because it runs in three places — the app server, the browser's
 * rules page and the scripts — and only one of them has one. Next.js is not
 * configured for `import text from "./zones.rules?raw"` here, and turning that
 * on would be a webpack/turbopack rule in `next.config.ts` that every one of
 * those three would have to agree about. So the text is *generated* into a
 * plain TypeScript module instead: one `files.ts` per game, written by this
 * script, checked in beside the `.rules` files it mirrors.
 *
 *   npx tsx scripts/arena-rulesets-emit.mts            rewrite every files.ts
 *   npx tsx scripts/arena-rulesets-emit.mts --check    fail if one is stale
 *
 * `--check` is what a commit hook or a reviewer runs: a `.rules` file edited
 * without regenerating would be a ruleset the app does not have.
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = path.join(process.cwd(), "src", "lib", "arena", "rulesets");
const check = process.argv.includes("--check");

const emit = (game: string): { file: string; text: string } => {
  const dir = path.join(ROOT, game);
  const names = fs
    .readdirSync(dir)
    .filter((n) => n.endsWith(".rules"))
    .sort();
  const entries = names.map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(fs.readFileSync(path.join(dir, n), "utf8"))},`);
  const body = entries.length ? [`export const FILES: Record<string, string> = {`, ...entries, `};`] : [`export const FILES: Record<string, string> = {};`];
  const text = [
    `/**`,
    ` * Generated by \`npm run arena:rulesets\` from \`src/lib/arena/rulesets/${game}/*.rules\`.`,
    ` * Do not edit: edit the \`.rules\` file and run the script again.`,
    ` *`,
    ` * The text lives here so the loader can be pure — see the script's header.`,
    ` */`,
    ...body,
    ``,
  ].join("\n");
  return { file: path.join(dir, "files.ts"), text };
};

const games = fs
  .readdirSync(ROOT, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();

let stale = 0;
for (const game of games) {
  const { file, text } = emit(game);
  const now = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "";
  if (now === text) {
    console.log(`rulesets: ${game} is up to date`);
    continue;
  }
  stale++;
  if (check) {
    console.error(`rulesets: ${path.relative(process.cwd(), file)} is stale — run \`npm run arena:rulesets\``);
    continue;
  }
  fs.writeFileSync(file, text);
  console.log(`rulesets: wrote ${path.relative(process.cwd(), file)}`);
}

if (check && stale) process.exit(1);
